
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WriteReadProjectDemo
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {

        this.OrderProduct = new HashSet<OrderProduct>();

    }


    public string ProductArticleNumber { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public int ProductCategory { get; set; }

    public int ProductManufacturer { get; set; }

    public decimal ProductCost { get; set; }

    public Nullable<byte> ProductDiscountAmount { get; set; }

    public int ProductQuantityInStock { get; set; }

    public Nullable<int> ProductStatus { get; set; }

    public int idEdIzm { get; set; }

    public Nullable<int> maxDiscount { get; set; }

    public int idSupplier { get; set; }

    public string ProductPhoto { get; set; }



    public virtual edIzm edIzm { get; set; }

    public virtual manufacture manufacture { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderProduct> OrderProduct { get; set; }

    public virtual ProductCategory ProductCategory1 { get; set; }

    public virtual supplier supplier { get; set; }

}

}
